add card api
trocco-io/embulk-input-twitter_ads_analytics pull request #21
Opened 2023-06-06 03:26 UTC by chikamura

add card api

2023-07-04 00:34 UTC, d-hrs requested changes
fix async option please.

2023-07-04 00:34 UTC, d-hrs commented on lib/embulk/input/twitter_ads_analytics.rb
> +          "async" => config.param("timezone", :bool, **optional_if_card),
![must-badge](https://img.shields.io/badge/review-must-red.svg)

```suggestion
          "async" => config.param("async", :bool, **optional_if_card),
```

2023-07-04 00:34 UTC, d-hrs commented on lib/embulk/input/twitter_ads/api.rb
> +        def get_sleep_sec(response:, retries:)
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)

duplicated with the following code:
https://github.com/trocco-io/embulk-input-twitter_ads_analytics/blob/44dd25302f46746f4fa670322b67a0b0e4bd52d5/lib/embulk/input/twitter_ads_analytics.rb#L408-L422

2023-07-04 00:34 UTC, d-hrs commented on lib/embulk/input/twitter_ads/card.rb
> +      class Card
![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)
👍 
we need refactoring to create a class for each resource.

2023-07-05 00:31 UTC, u110 approved these changes

2023-07-05 01:21 UTC, d-hrs approved these changes
LGTM

2023-07-05 01:21 UTC, merged