API V10
trocco-io/embulk-input-twitter_ads_analytics pull request #7
Opened 2022-02-15 06:46 UTC by yukitotora

2022-02-15 08:10 UTC, kekekenta approved these changes

2022-02-17 04:09 UTC, d-hrs requested changes
バージョンの変更お願いします

2022-02-17 04:09 UTC, d-hrs commented on embulk-input-twitter_ads_analytics.gemspec
> +  spec.version = "0.2.1"
apiのバージョン変えるって結構大きな変更なので、0.3.0にしてもらえると。
プラグインは、基本的にセマンティックバージョニングをしています
https://semver.org/lang/ja/

2022-02-17 07:10 UTC, yukitotora commented on embulk-input-twitter_ads_analytics.gemspec
> +  spec.version = "0.2.1"
了解です！

2022-02-17 07:57 UTC, d-hrs approved these changes

2022-02-17 10:03 UTC, merged